name: TEST Predict Action

on: [workflow_dispatch]

jobs:
  predict-cost:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      - name: local action with raw yaml
        id: raw-prediction
        uses: ./
        with:
          log_level: "warn"
          path: ./test

      - name: output raw yaml prediction
        run: |
          echo "${{ steps.raw-prediction.outputs.PREDICTION_TABLE }}"

      - name: download templated kubecost yaml
        run: |
          curl \
              https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/kubecost.yaml \
              --silent \
              --output ./kubecost.yaml

      - name: local action with kubecost yaml
        id: kubecost-raw-prediction
        uses: ./
        with:
          log_level: "debug"
          path: ./kubecost.yaml

      - name: output kubecost yaml prediction
        run: |
          echo "${{ steps.kubecost-raw-prediction.outputs.PREDICTION_TABLE }}"
